apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoution
  template:
    metadata:
      labels:
        app: hoution
    spec:
      containers:
      - image: okteto.dev/hoution:latest
        name: hoution
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.lenskart.com"
        - name: Vless_UUID
          value: "ef77d9bc-9b14-4460-a5d5-aa5ccf6780c7"
        - name: Vless_Path
          value: "/poisdrty"
        - name: Vmess_UUID
          value: "ef77d9bc-9b14-4460-a5d5-aa5ccf6780c7"
        - name: Vmess_Path
          value: "/er7ygokh"
        - name: Share_Path
          value: "/Share470"
