apiVersion: apps/v1
kind: Deployment
metadata:
  name: upgreat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upgreat
  template:
    metadata:
      labels:
        app: upgreat
    spec:
      containers:
      - image: okteto.dev/upgreat:latest
        name: upgreat
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.crazygames.com"
        - name: Vless_UUID
          value: "35445f8a-2177-4aef-83a8-6dc2aa4366c7"
        - name: Vless_Path
          value: "/isxu5y9o"
        - name: Vmess_UUID
          value: "35445f8a-2177-4aef-83a8-6dc2aa4366c7"
        - name: Vmess_Path
          value: "/TYUJ6RT"
        - name: Share_Path
          value: "/Share542"
