apiVersion: apps/v1
kind: Deployment
metadata:
  name: shouit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shouit
  template:
    metadata:
      labels:
        app: shouit
    spec:
      containers:
      - image: okteto.dev/shouit:latest
        name: shouit
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.canva.com"
        - name: Vless_UUID
          value: "e55ecbd7-5fa4-4e88-ab02-c7d91f56de06"
        - name: Vless_Path
          value: "/sdojt8u2e"
        - name: Vmess_UUID
          value: "e55ecbd7-5fa4-4e88-ab02-c7d91f56de06"
        - name: Vmess_Path
          value: "/vbnjitgf"
        - name: Share_Path
          value: "/Share360"
