apiVersion: apps/v1
kind: Deployment
metadata:
  name: swretiony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swretiony
  template:
    metadata:
      labels:
        app: swretiony
    spec:
      containers:
      - image: okteto.dev/swretiony:latest
        name: swretiony
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.greenmangaming.com"
        - name: Vless_UUID
          value: "d737ba60-0657-4bb0-b936-07c71a4fc3ca"
        - name: Vless_Path
          value: "/eB4usdyi"
        - name: Vmess_UUID
          value: "d737ba60-0657-4bb0-b936-07c71a4fc3ca"
        - name: Vmess_Path
          value: "/ertjxcvu"
        - name: Share_Path
          value: "/Share423"
