apiVersion: apps/v1
kind: Deployment
metadata:
  name: yerctvio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yerctvio
  template:
    metadata:
      labels:
        app: yerctvio
    spec:
      containers:
      - image: okteto.dev/yerctvio:latest
        name: yerctvio
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "31126297-406e-4935-b170-01195107310b"
        - name: Vless_Path
          value: "/gt7ikmnb"
        - name: Vmess_UUID
          value: "31126297-406e-4935-b170-01195107310b"
        - name: Vmess_Path
          value: "/prsHBk"
        - name: Share_Path
          value: "/Share921"
